/** @type {import('tailwindcss').Config} */
export default {
   content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
   ],
   darkMode: "class",
   theme: {
      extend: {
         colors: {
            "on-surface": "#191c1e",
            "secondary": "#006c49",
            "background": "#f7f9fb",
            "on-primary-container": "#cad3ff",
            "tertiary-fixed-dim": "#ffb59c",
            "surface-tint": "#2151da",
            "on-tertiary": "#ffffff",
            "surface-container-low": "#f2f4f6",
            "secondary-fixed": "#6ffbbe",
            "secondary-fixed-dim": "#4edea3",
            "on-surface-variant": "#434655",
            "on-secondary": "#ffffff",
            "primary-fixed-dim": "#b7c4ff",
            "on-error": "#ffffff",
            "on-error-container": "#93000a",
            "on-secondary-container": "#00714d",
            "on-tertiary-container": "#ffc9b7",
            "inverse-surface": "#2d3133",
            "surface-variant": "#e0e3e5",
            "primary-fixed": "#dce1ff",
            "tertiary": "#7f2500",
            "surface-bright": "#f7f9fb",
            "secondary-container": "#6cf8bb",
            "on-background": "#191c1e",
            "surface-container-lowest": "#ffffff",
            "tertiary-container": "#a73400",
            "surface-dim": "#d8dadc",
            "on-secondary-fixed": "#002113",
            "surface-container": "#eceef0",
            "inverse-primary": "#b7c4ff",
            "outline": "#747686",
            "on-tertiary-fixed": "#390c00",
            "surface": "#f7f9fb",
            "error": "#ba1a1a",
            "error-container": "#ffdad6",
            "surface-container-high": "#e6e8ea",
            "on-tertiary-fixed-variant": "#832700",
            "on-primary-fixed-variant": "#0039b5",
            "on-primary": "#ffffff",
            "primary-container": "#1d4ed8",
            "outline-variant": "#c4c5d7",
            "on-primary-fixed": "#001551",
            "inverse-on-surface": "#eff1f3",
            "tertiary-fixed": "#ffdbcf",
            "on-secondary-fixed-variant": "#005236",
            "primary": "#0037b0"
         },
         fontFamily: {
            "headline": ["Manrope", "sans-serif"],
            "body": ["Inter", "sans-serif"],
            "label": ["Inter", "sans-serif"]
         }
      },
   },
   plugins: [],
}
